//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainLevel
    {
        public MainLevel()
        {
            this.SubLevels = new HashSet<SubLevel>();
        }
    
        public int LevelId { get; set; }
        public string LevelName { get; set; }
    
        public virtual ICollection<SubLevel> SubLevels { get; set; }
    }
}
